### PR TITLE
Fork documentation for Moodle 4.5

### PR DESCRIPTION
**Pull request by junpataleta**
Part of the [2 weeks after the release process ](https://moodledev.io/general/development/process/release#2-weeks-after)

### CODE REVIEW

**Comment by andrewnicols** [comment]
Note: I haven’t done this because I wanted to check if we should remove the 4.2 docs first to avoid excessive documentation bloat

**Comment by junpataleta** [comment]
Hi, @andrewnicols. Can't we deal with that on a separate issue instead?

**Comment by andrewnicols** [comment]
We can but then we are building more docs for longer which makes the build
bigger and slower. That’s the only reason I was holding off.

It it’s building fine then we an land this now :)

Andrew Lyons
Principal Architect

Moodle HQ - moodle.com [image: Moodle - Empowering educators to improve our
world] <https://moodlemoot.org>
Join the Moodle Community at #MootGlobal24. Mérida, México, 22-24 October
2024

**Review by HuongNV13 — APPROVED** [review]

**Comment by HuongNV13** [comment]
Thanks, Jun.
It looks good to me.
Since this PR was built successfully, I guess we can land this and create another PR to remove the 4.2's devdocs

**Pull request merged**
