### PR TITLE
Add add_sticky_action_buttons to forms doc (MDL-77635)

### PR DESCRIPTION
**Pull request by ilyatregubov**

### CODE REVIEW

**Review by sarjona — CHANGES_REQUESTED** [review]
Hola @ilyatregubov!
Thanks for updating this page. The text looks good but I have a question for you: shouldn't a reference to this method be added to docs/devupdate page? That way it will be easier for devs to be aware of its existence :-)

**Review by andrewnicols — APPROVED** [review]

**Review by andrewnicols — CHANGES_REQUESTED** [review]
In addition to the devupdate, can we add a `<since>` tag to this please.

kthxbye :)

**Comment by ilyatregubov** [comment]
Updated branch - added to  docs/devupdate page and added tag. I only added tag to forms page itself since  docs/devupdate page is for 4.3 on whole

**Review by sarjona — APPROVED** [review]
Thanks for working on this and adding the missing points (Since + dev update reference). It looks great so I'm happy to approve it :-)

**Review by sarjona — APPROVED** [review]

**Pull request merged**
