### PR TITLE
yarn build

### PR DESCRIPTION
**Pull request by notebook-t**
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/750"></a>

### CODE REVIEW

**Comment by andrewnicols** [comment]
Sorry, but what is this change? We only support one version of Node.
We also do not recommend using npm
And I'm not sure why we want to run webpack?

**Review by notebook-t — COMMENTED** [review]
string = 'production': 'none' | 'development' | 'production'

**Comment by andrewnicols** [comment]
Please explain the purpose of this patch. Your previous comment is
meaningless without context.

**Review by notebook-t — COMMENTED** [review]
#750 

>

**Pull request closed without merging**
