### PR TITLE
[docs] Documentation for MDL-81821

### PR DESCRIPTION
**Pull request by roland04**
This PR is related to https://tracker.moodle.org/browse/MDL-81821

### CODE REVIEW

**Comment by andrewnicols** [comment]
Pinging @ferranrecio to review this PR.

**Comment by roland04** [comment]
Thanks Ferran! Rebased :+1:

**Comment by ferranrecio** [comment]
Thanks for the rebase. Ready to merge.

**Review by ferranrecio — APPROVED** [review]
Patch tested and reviewed. Ready to merge.

**Pull request merged**
