### PR TITLE
[docs] Updates for 404 minor release

### PR DESCRIPTION
**Pull request by mickhawkins**
Updates and additions for Monday's upcoming minor release.

<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/351"></a>

### CODE REVIEW

**Comment by scara** [comment]
Hello Everyone,
to avoid updating the PNG on each change in the release graph, [mermaid](https://mermaid-js.github.io/mermaid/#/gantt) could be an option:
- Docusaurus has no OOTB support yet but it is quite there: https://github.com/facebook/docusaurus/pull/7490#issuecomment-1237580357
- Since 2.0 you can add your own components in Docusaurus i.e. you can already add mermaid support here via https://github.com/sjwall/mdx-mermaid#quick-start-with-docusaurus (https://sjwall.github.io/mdx-mermaid/docs/examples/#code-block)

HTH,
Matteo

**Review by andrewnicols — APPROVED** [review]

**Comment by andrewnicols** [comment]
Hi @scara,

> Hello Everyone, to avoid updating the PNG on each change in the release graph, [mermaid](https://mermaid-js.github.io/mermaid/#/gantt) could be an option:
> 
> * Docusaurus has no OOTB support yet but it is quite there: [feat: support mermaid code blocks in Markdown facebook/docusaurus#7490 (comment)](https://github.com/facebook/docusaurus/pull/7490#issuecomment-1237580357)
> * Since 2.0 you can add your own components in Docusaurus i.e. you can already add mermaid support here via https://github.com/sjwall/mdx-mermaid#quick-start-with-docusaurus (https://sjwall.github.io/mdx-mermaid/docs/examples/#code-block)

We're aware of this and already have support for Mermaid in our repo via Remark. I'm a follower of the issue to add native support too.

I have already tried to create this in Mermaid but none of the graph types are very suited to the release graph so we were going to look at automatically generating an SVG based on the data that we already hold. It's worth noting that we do have [all of the version data in a nice, digestable, validated, JSON format](https://github.com/moodle/devdocs/blob/main/data/versions.json) which means that this should be really quite easy to manage once we get to it. I suspect we'll probably do it as some kind of build step (`docusaurus release-graphs` or similar).

It's quite a low priority item at the moment but it is definitely on the radar.

**Comment by scara** [comment]
Hi @andrewnicols,
> I have already tried to create this in Mermaid but none of the graph types are very suited to the release graph so we were going to look at automatically generating an SVG based on the data that we already hold.

Sounds great!

Matteo

**Comment by andrewnicols** [comment]
Thanks Matteo,

We already have Mermaid support and we intend to switch the graph at some
point but haven’t quite gotten round to it yet. We may actually do it as an
SVG because the mermaid graph just isn’t quite there when I tried. There
isn’t a suitable graph for it and the ones that are close just don’t quite
work.

**Pull request merged**
