### PR TITLE
Starting to draft 'A better contribution' guides

### PR DESCRIPTION
**Pull request by andrewnicols**

### CODE REVIEW

**Comment by andrewnicols** [comment]
Hi Tim,

This is currently in draft status - let me know if/when you're ready and I'd be happy to review it and merge it.

**Comment by timhunt** [comment]
Right, I have just reviewed this, and apart from having to correct two one-charater typos, and rebase, I think this is ready to be merged as as useful starting point.

Once that is done I will think about writing one or two more useful guides. E.g. migrating https://docs.moodle.org/dev/Commit_cheat_sheet into what we want to say about git usage.

**Comment by andrewnicols** [comment]
Hi Tim,

Is this ready to come out of Draft status?

**Comment by timhunt** [comment]
I think so.

**Pull request merged**
