### PR TITLE
[docs] Migrate Database Schema

### PR DESCRIPTION
**Pull request by davewoloszyn**

### CODE REVIEW

**Review by sarjona — CHANGES_REQUESTED** [review]
Hi @davewoloszyn!
Thanks for migrating this page. The patch looks good. However, before integrating it, it would be great if you could review the commits and remove the merge commit you've added (your branch should contain only the "[docs] Migrate Database Schema]" commit).

**Comment by davewoloszyn** [comment]
Hi @sarjona,
My apologies, I have corrected that. Can you please take another look?

**Review by sarjona — APPROVED** [review]
Hi @davewoloszyn!
Thanks for reviewing the git history and removing the merge commit! <3

**Comment by sarjona** [comment]
As now there is also a versioned folder for 4.1, I've also copied the docs/apis/core/dml/database-schema.md migrated page into versioned_docs/version-4.1/apis/core/dml/database-schema.md.

Merged :-) 

Good job, @davewoloszyn!!

**Pull request closed without merging**
