### PR TITLE
[repo] Migrate Yarn to Yarn2

### PR DESCRIPTION
**Pull request by andrewnicols**
Following https://yarnpkg.com/getting-started/migration and not using zero-installs.

<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/395"></a>

### CODE REVIEW

**Comment by andrewnicols** [comment]
@timhunt if you're able to try this on your Windows setup that would be great.

**Comment by timhunt** [comment]
It certainly would. However, I have an OU internal deadline and an OU choir concert coming up, so probably won't be this coming week. remind me the week after if I seem to have forgotten.

**Comment by sarjona** [comment]
@timhunt whenever you can, it would be great if you could confirm this fixes the issues you faced in Windows :-) Thanks in advance for your help!!! :-*

**Comment by timhunt** [comment]
I just started looking at this.

However, it turns out I don't know what I am doing.

Andrew's commit to swtich to Yarn2 does not include any changes to the 'getting started with contributing to dev docs'.

Also, I can't easily find where "getting started with contributing to dev docs" is hidden in the current dev docs.

Any hints

**Comment by timhunt** [comment]
OK, found it: https://moodledev.io/general/documentation/installation

**Comment by timhunt** [comment]
```
$ git fetch git@github.com:andrewnicols/devdocs.git yarnMigration
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 9 (delta 3), reused 3 (delta 3), pack-reused 6
Unpacking objects: 100% (9/9), done.
From github.com:andrewnicols/devdocs
 * branch                yarnMigration -> FETCH_HEAD
```
```
$ git checkout FETCH_HEAD
Note: checking out 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7bda6aa8d [repo] Migrate Yarn to Yarn2
```
```
$ node -v
v16.14.0
```
```
$ rm -rf
```
```
npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice
npm notice New major version of npm available! 8.3.1 -> 9.1.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.1.2>
npm notice Run `npm install -g npm@9.1.2` to update!
npm notice
npm ERR! process terminated
npm ERR! signal SIGINT

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tjh238\AppData\Local\npm-cache\_logs\2022-11-29T13_21_38_873Z-debug-0.log
```

Well, that is not good.

**Comment by timhunt** [comment]
Another try (in a clean folder):

```
$ git clone git@github.com:andrewnicols/devdocs.git -b yarnMigration devdocs-yarn2-test
Cloning into 'devdocs-yarn2-test'...
remote: Enumerating objects: 19804, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 19804 (delta 11), reused 12 (delta 11), pack-reused 19789
Receiving objects: 100% (19804/19804), 42.42 MiB | 4.46 MiB/s, done.
Resolving deltas: 100% (14126/14126), done.
Checking out files: 100% (1010/1010), done.
```
```
$ cd devdocs-yarn2-test/
```
```
$ npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> devdocs@4.0 prepare
> husky install

husky - Git hooks installed

added 2105 packages, and audited 2106 packages in 6m

319 packages are looking for funding
  run `npm fund` for details

35 vulnerabilities (4 moderate, 31 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
```
npx yarn -v
3.2.4
```
```
$ npx yarn install
[SNIP some initial messages, which disappoared from my terminal buffer, because there were then approximately three million, seven hundred and fourty two* "... can't be found in the cache and will be fetched from the remote registry" messages which seems a bit excessive! (* number is approximate;-))]
➤ YN0013: │ typescript@npm:4.9.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.9.3#~builtin<compat/typescript>::version=4.9.3&hash=701156: Cannot apply hunk #8
➤ YN0000: └ Completed in 2m 9s
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:3.26.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.26.1 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5m 26s
➤ YN0000: Done with warnings in 7m 53s
```
```
$ npx yarn start
[INFO] Starting the development server...
[WARNING] No docs found in "releases\4.0": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.11": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.9": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.10": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.8": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.7": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.6": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.5": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.4": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.3": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.2": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.1": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\3.0": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.9": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.8": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.7": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.6": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.5": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.4": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.3": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.2": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.1": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\2.0": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.9": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.8": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.7": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.6": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.5": can't auto-generate a sidebar.
[WARNING] No docs found in "releases\1.4": can't auto-generate a sidebar.
[SUCCESS] Docusaurus website is running at: http://localhost:3000/devdocs/
i Compiling Client
√ Client: Compiled successfully in 1.37m
client (webpack 5.75.0) compiled successfully
```

OK, so that does seem to work, just with a lot of noise. Not sure why my first attempt failed. Anyway, hope that is of some help. Let me know if I can do anything else.

**Comment by andrewnicols** [comment]
Thanks Tim - much appreciated.

The noise is because of a bug in our releases sidebar configuration and I think that shouldbe easy to address.

Note: yarn is a replacement for npm, so you should only need to run `yarn`, and never `npm install`.

I'll keep tweaking this and will hopefully send it for review soon. Thanks!!

**Comment by sarjona** [comment]
@timhunt I've only been able to find a reference to npm in https://moodledev.io/general/documentation/installation#local-development (the one that Andrew mentioned to install yarn). Once yarn is installed, npm is not required any more. Is there any other page containing the wrong information that I missed? TIA!

**Comment by timhunt** [comment]
> @timhunt I've only been able to find a reference to npm in https://moodledev.io/general/documentation/installation#local-development (the one that Andrew mentioned to install yarn). Once yarn is installed, npm is not required any more. Is there any other page containing the wrong information that I missed? TIA!

Right, that is the dev docs install instructions. To me, that says you need npm.

**Comment by sarjona** [comment]
@timhunt if you have a proposal to improve the wording and clarify it, I'll be more than happy to review and merge it ;-)

**Comment by andrewnicols** [comment]
I'm making the call to self-merge this change in the interests of getting things moving.

I've adjusted the installation instructions to:
```
# Install the correct version of NodeJS using NVM:
nvm install

# Enable corepack:
corepack enable

# Run yarn
yarn
```

**Pull request merged**
