### PR TITLE
Create Updates.md

### PR DESCRIPTION
**Pull request by federico-moodle**
First changes on the main page of the Plugins Directory from the Plugins Directory Improvements project.

### CODE REVIEW

**Comment by vmdef** [comment]
Thank you for creating this new page and for fixing the errors detected by the linter.

**Review by vmdef — APPROVED** [review]
All the format errors have adequately been addressed.

**Comment by andrewnicols** [comment]
Folks, this has incorrect casing. We don't want uppercase filenames please.

**Comment by andrewnicols** [comment]
#799

**Comment by vmdef** [comment]
My fault. Thanks for fixing it, @andrewnicols.

**Pull request merged**
